### ISSUE TITLE
输入序号后报错了

### ISSUE THREAD

**Issue by sevenplus310** [Tongrens/SubmitTool#2]
请选择需要提交的表单序号
序号：1         名称：test              状态：进行中
请输入序号：1
Traceback (most recent call last):
  File "SubmitTool.py", line 154, in <module>
    main.main()
  File "SubmitTool-main.zip.35c\SubmitTool-main\SubmitTool.py", line 144, in main
    SubmitTool(history_data[int(user_input) - 1]['eid'], token).main()  # 选择eid并进行提交
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ubmitTool-main.zip.35c\SubmitTool-main\SubmitTool.py", line 71, in main
    self.get_user_info()
  File "SubmitTool-main.zip.35c\SubmitTool-main\SubmitTool.py", line 21, in get_user_info
    self.extra_info[i['name']] = i['value']

TypeError: unhashable type: 'list'

**Comment by Tongrens** [comment]
已修复
[1.0.3.2](https://github.com/Tongrens/SubmitTool/releases/tag/v1.0.3.2)
